[package]
name = "basic_08"
version = "0.1.0"
authors = ["Ignacio Carbajo <icarbajop@gmail.com>"]

[dependencies]
error-chain = "0.10"
oauth-client = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde-transcode = "*"
